/* TABLA CIUDADES */
CREATE TABLE IF NOT EXISTS 'Ciudad' (
id_ciudad INTEGER PRIMARY KEY NOT NULL,
nombre_ciudad TEXT NOT NULL
);

/* TABLA AREA */
CREATE TABLE IF NOT EXISTS 'Area' (
id_area INTEGER PRIMARY KEY NOT NULL,
nombre_area TEXT NOT NULL,
ciudad_id INTEGER NOT NULL,
CONSTRAINT FK_CIUDAD FOREIGN KEY(ciudad_id) REFERENCES 'Ciudad'(id_ciudad)
);

/* TABLA FUENTE */
CREATE TABLE IF NOT EXISTS 'Fuente'(
id_fuente INTEGER PRIMARY KEY NOT NULL,
descripcion TEXT NOT NULL,
coordenadas TEXT NOT NULL,
area_id INTEGER NOT NULL,
CONSTRAINT FK_AREA FOREIGN KEY(area_id) REFERENCES 'Area'(id_area)
);