/* INSERCIONES DE CIUDAD */
INSERT INTO ciudad VALUES(0, 'Logroño');
/* INSERCION DE AREAS */
INSERT INTO area VALUES(0, 'Parque del Ebro', 0);
INSERT INTO area VALUES(1, 'Plaza del Mercado', 0);
/* INSERCION DE LOCALICACION */
INSERT INTO localizacion VALUES(0, 'DESCRIPCION LOCALIZACION', 'COORDENADAS', 0);
INSERT INTO localizacion VALUES(1, 'DESCRIPCION LOCALIZACION', 'COORDENADAS', 0);
INSERT INTO localizacion VALUES(2, 'DESCRIPCION LOCALIZACION', 'COORDENADAS', 1);
/* INSERCION DE fUENTES */
INSERT INTO fuente VALUES(0, 'DESCRIPCION FUENTE', 'fOTO', 0);
INSERT INTO fuente VALUES(1, 'DESCRIPCION FUENTE', 'fOTO', 0);
INSERT INTO fuente VALUES(2, 'DESCRIPCION FUENTE', 'fOTO', 1);